In [1]:
# np.array
import numpy as np
a=np.array([2,4,56,67,7])
print(a)
print(type(a))



[ 2  4 56 67  7]
<class 'numpy.ndarray'>


In [67]:
#2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b)
print()
c=np.array([[[1,2,3,4],[4,5,6,7],[5,6,2,7]]])
print(c)

[[1 2 3]
 [4 5 6]]

[[[1 2 3 4]
  [4 5 6 7]
  [5 6 2 7]]]


In [68]:
#dtype
F=np.array([1,2,3],dtype=float)
print(F)

g=np.array([1,2,3],dtype=bool)
print(g)

h=np.array([1,2,3],dtype=complex)
print(h)


[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [69]:
#np.arange
np.arange(1,11)
#np.arange(1,11,2)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
# with reshape
#np.arange(1,11).reshape(5,2) #5 row and 2 column
np.arange(1,11).reshape(2,5) #2 row and 5column

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
#
import numpy as np
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
#np.random
np.random.random((3,4))

array([[0.04720085, 0.75197737, 0.99024189, 0.16833022],
       [0.16528197, 0.67571269, 0.20726504, 0.13379514],
       [0.41806066, 0.08279295, 0.68471028, 0.08942485]])

In [74]:
#np.linspace  (linear space)
np.linspace(-10,5,10)


array([-10.        ,  -8.33333333,  -6.66666667,  -5.        ,
        -3.33333333,  -1.66666667,   0.        ,   1.66666667,
         3.33333333,   5.        ])

In [75]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [76]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim find the dimension of array
print(a1.ndim) # 1
print(a2.ndim) # 2
print(a3.ndim) # 3
print(a1)


1
2
3
[0 1 2 3 4 5 6 7 8 9]


In [78]:
# shape 
print(a1.shape) # 1o
print(a2.shape) # (3,4)
print()
print(a3.shape)
print(a3)




(10,)
(3, 4)

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [79]:
# size find the no of items
print(a1.size)
print(a1)
print(a2.size)
print(a2)
print(a3.size)
print(a3)

10
[0 1 2 3 4 5 6 7 8 9]
12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [80]:
# itemsize find the size of array in memory
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [81]:
# dtype find the data type of array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [82]:
# astype 
a1.astype(np.float64)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
# array operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [84]:
#scalar operation
#Arithematic operation add sub multiply divide modulo etc
add=a1+2
print(add)
sub=a1-4
print(sub)
# relationl operations <, >,<=,>= etc
geater=a1>4
print(geater)
print(a1<5)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-4 -3 -2 -1]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [85]:
# vector operation
#1 arithematic operation
add1=(a1 + a2)
print(a1)
print(a2)
print(" add",add1)

#2 relational operatoin
print(a1<a2)
print(a1>a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
 add [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [86]:
# max/ min/ sum/prod

print("maximum number", np.max(a1))
print("minimum ", np.min(a1))
print("sum of array ", np.sum(a1))

# 0 -> col and 1-> row
print("maximum no of  each row",np.max(a1,axis=1))
print("maximum no of each column",np.max(a1,axis=0))

maximum number 11
minimum  0
sum of array  66
maximum no of  each row [ 3  7 11]
maximum no of each column [ 8  9 10 11]


In [87]:
# mean /median/ std/var
print("mean",np.mean(a1))
print("median" ,np.median(a1))
print( "stander deviation",np.std(a1))
print("variation", np.var(a1))


mean 5.5
median 5.5
stander deviation 3.452052529534663
variation 11.916666666666666


In [88]:
# np.dot   dot product
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
print(np.dot(a2,a1))


[[164 203 242 281]
 [200 248 296 344]
 [236 293 350 407]
 [272 338 404 470]]


In [89]:
# log and exponents
#print(np.log(a1))
print(np.exp(a1))


[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [90]:
#round/floor/ceil
item=np.random.random((2,3))*100
print(item)
print(np.round(item))
print(np.floor(item))
print(np.ceil(item))



[[79.8829248  88.79981242 89.04229195]
 [56.9053424  29.67273282 50.71658359]]
[[80. 89. 89.]
 [57. 30. 51.]]
[[79. 88. 89.]
 [56. 29. 50.]]
[[80. 89. 90.]
 [57. 30. 51.]]


In [91]:
# indexing and slicing
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1[-1])
print(a2)
print(a2[1,2])#6 first iis row and second is column
print(a2[2,3])#11
print(a2[2,2])#10
print(a2[2,0])#8
print(a2[-1,-4])


9
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11
10
8
8


In [92]:
print(a3)
print(a3[1,0,1])#5 first 1d or 2d second row and third column
print(a3[0,1,0])#2

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
2


In [34]:
#slicing 
import numpy as np
a4=np.arange(12)
a5=np.arange(12).reshape(3,4)
print(a4)
print(a4[1:5])
print(a5)
print(a5[0,:])#row
print(a5[1,:])#row
print(a5[2,:])#row
print(a5[:,0])#column
print(a5[:,1])#column
print(a5[:,2])#column
print(a5[:,3])#column

print(a5[1:,1:3])
# print(a5[::2,::3]) #corner item
# print(a5[::2,1::2])
# print(a5[1,::3])
# print(a5[:2:,1:])#[[1 2 3]  [5 6 7]]




[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2 3 4]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


In [35]:
# 3D array slicing
a6=np.arange(27).reshape(3,3,3)
print(a6)
print(a6[1]) # midle array
print(a6[2])
print(a6[1,1,1])#13
print(a6[0,1,:])
print(a6[1,:,1])
print(a6[2,1:,1:])
print(a6[::2,0,::2])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
13
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [39]:
#iterating
print(a4)
for i in a4:
    print(i)
    

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [45]:
print(a5)
for i in a5:
    print(i)
    
for i in np.nditer(a5):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [43]:
for i in a6:
    print(i)

for i in np.nditer(a6):
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [47]:
# transpose   
print(a5)
print(np.transpose(a5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [50]:
# revel  
print(a5)
print(a5.ravel()) # change to single dimenstional

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [56]:
# horizontal stacking 
ar=np.arange(12).reshape(3,4)
ar1=np.arange(12,24).reshape(3,4)
print(ar)
print(ar1)
print(np.hstack((ar ,ar1)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [57]:
#vertical stacking
print(np.vstack((ar ,ar1)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
#horizontal splitting
import numpy as np
ar=np.arange(16).reshape(4,4)
print(ar)
print(np.hsplit(ar,2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [13]:
#vertical splitting
print(np.vsplit(ar,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
